- name: Start RGB App
  hosts: raspberrypis
  become: true

  vars:
    ansible_ssh_private_key_file: /home/roger/.ssh/raspberrypi
    packages: [libffi-dev, libssl-dev, python3-dev, python3, python3-pip, git]
  tasks:
    - name: Install Packages
      apt:
        name: '{{packages}}'
        update_cache: yes
        autoremove: yes

    - name: Download Docker
      shell: 'curl -fsSL test.docker.com -o get-docker.sh'
      args:
        creates: /home/pi/get-docker.sh

    - name: Install Docker
      shell: 'sh /home/pi/get-docker.sh'
      args:
        creates: /usr/bin/docker

    - name: Add Pi to Docker UserGroup
      shell: 'sudo usermod -aG docker pi'
    - name: Install docker-compose
      shell: 'sudo pip3 install docker-compose'
      args:
        creates: /usr/local/bin/docker-compose

    - name: Enable Docker
      shell: 'sudo systemctl enable docker'

    - name: Cleanup Docker Install Script
      shell: 'rm -rf get-docker.sh'
      args:
        removes: '/home/pi/get-docker.sh'

    - name: Pull down project
      shell: 'git clone https://github.com/Rogersiver/python-osc-test'
      args:
        creates: '/home/pi/python-osc-test/'

    - name: Start Application
      become: True
      shell:
        cmd: 'docker-compose -f docker-compose.yml up -d'
        chdir: /home/pi/python-osc-test/

    - name: Get info
      docker_host_info:
        containers: True
      register: result
