- name: Start RGB App
  hosts: raspberrypis
  become: true

  vars:
    packages: [libffi-dev, libssl-dev, python3-dev, python3, python3-pip, git]
  tasks:
    - name: Install Packages
      apt:
        name: '{{packages}}'
        update_cache: yes
        autoremove: yes

    - name: Download Docker
      shell: 'curl -fsSL test.docker.com -o get-docker.sh'
      args:
        creates: /home/pi/get-docker.sh

    - name: Install Docker
      shell: 'sh /home/pi/get-docker.sh'
      args:
        creates: /usr/bin/docker

    - name: Add Pi to Docker UserGroup
      shell: 'sudo usermod -aG docker pi'
    - name: Install docker-compose
      shell: 'sudo pip3 install docker-compose'
      args:
        creates: /usr/local/bin/docker-compose

    - name: Enable Docker
      shell: 'sudo systemctl enable docker'

    - name: Cleanup Docker Install Script
      shell: 'rm -rf get-docker.sh'

    - name: Pull down project
      shell: 'git clone https://github.com/Rogersiver/python-osc-test'

    - name: Enter Project Directory
      shell: 'cd python-osc-test && sudo docker-compose up'
