 # syntax=docker/dockerfile:1
 FROM python:3.10.8-buster

 WORKDIR /python-docker

 COPY /venv/requirements.txt requirements.txt

 RUN pip3 install -r requirements.txt

 COPY . .

 CMD ["flask", "--app",  "flaskr", "--debug", "run", "--host=0.0.0.0"]


