 # syntax=docker/dockerfile:1
 FROM python:3.10.8-buster

 WORKDIR /python-docker

 COPY /venv/requirements.txt requirements.txt

 RUN pip3 install -r requirements.txt

 COPY . .

 EXPOSE 5000
 EXPOSE 7771

 CMD ["python3", "server"]


